image: i386/gcc:6.1

pipelines:
  default:
    - step:
        script:
          - PATH=$PATH:$PWD/Linux/386/bin MKFLAGS='SYSHOST=Linux OBJTYPE=386 ROOT='$PWD 
          - mk $MKFLAGS mkdirs
          - mk $MKFLAGS emuinstall
          - emu cat /dev/sysctl || echo ' -' exited with status $? '(ignored)'
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"Linux/386/bin/emu"
