SYSTARG=MacOSX
<../../mkconfig
SYSTARG=MacOSX

#Configurable parameters

CONF=emu			#default configuration
CONFLIST=emu
CLEANCONFLIST=emu emu-g emu-carbon emu-x11

INSTALLDIR=$ROOT/$SYSTARG/$OBJTYPE/bin	#path of directory where kernel is installed

#end configurable parameters

<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE	#set vars based on target system

<| $SHELLNAME ../port/mkdevlist $CONF	#sets $IP, $DEVS, $PORT, $LIBS, etc

OBJ=\
	asm-$OBJTYPE.$O\
	$CONF.root.$O\
	lock.$O\
	$DEVS\
	$PORT\

HFILES=\

CFLAGS='-DROOT="'$ROOT'"'\
	'-DOBJTYPE="'$OBJTYPE'"'\
	-DEMU -I. -I../port\
	-I$ROOT/$SYSTARG/$OBJTYPE/include\
	-I$ROOT/include -I$ROOT/libinterp\
	$CTHREADFLAGS $CFLAGS $EMUOPTIONS\

KERNDATE=`{$NDATE}

SYSLIBS= \
	-lm\
	-lpthread\
	-framework CoreFoundation\
	-framework IOKit\
	$SYSLIBS

default:V:	$O.$CONF

<../port/portmkfile

$O.$CONF:	$OBJ $CONF.c $CONF.root.h $LIBFILES
	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
	$LD $LDFLAGS -o $target $OBJ $CONF.$O $LIBFILES $SYSLIBS

install:V: $O.$CONF
	cp $O.$CONF $INSTALLDIR/$CONF

devfs.c:N:	../port/devfs-posix.c

%-objc.$O: %.m
	$CC $CFLAGS -o $target $stem.m
